name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run tests
        run: script/cibuild
